<div class="statusBar">
	<div class="statusBarProgress" style="width: ;"></div>
	<span class="statusStep statusStep1 statusStepActive">1</span>
	<span class="statusStep statusStep2">2</span>
	<span class="statusStep statusStep3">3</span>
	<p>
		<span class="statusStepText statusStepText1"> Créez votre t-shirt</span>
		<span class="statusStepText statusStepText2"> Définissez votre objectif</span>
		<span class="statusStepText statusStepText3"> Ajoutez une description</span>
	</p>
</div>