	<div class="fpd-product" title="Base" data-thumbnail="<?php echo $this->basePath(); ?>/img/shirt/P_M528_ST_Leads_Front_Black.png">
	    <img src="<?php echo $this->basePath(); ?>/img/shirt/P_M528_ST_Leads_Front_Black.png" title="T-shirt" data-parameters='{"colors": "#3086e7,#ffffff,#990000", "price": 20, "scale": 0.7, "autoCenter": true}' />
	    <img src="<?php echo $this->basePath(); ?>/img/shirt/limit.png" title="limit" data-parameters='{"x": 378, "y": 370, "scale": 0.7, "autoCenter": false}'>
	    <span title="OuiShirt" data-parameters='{"x": 100, "y": 250, "removable": true, "draggable": true, "rotatable": true, "resizable": true, "colors": "#3086e7", "textSize": 48, "boundingBox": "limit"}' >OuiShirt</span>
	</div>

	
	<div class="fpd-product" title="TITLE" data-thumbnail="<?php echo $this->basePath(); ?>/img/shirt/P_M528_ST_Leads_Back_Black.png">
	    <img src="<?php echo $this->basePath(); ?>/img/shirt/P_M528_ST_Leads_Back_Black.png" title="P_M528_ST_Leads_Back_Black" data-parameters='{"x": 100, "y": 200, "price": 20, "scale": 0.7}' />
	    <img src="<?php echo $this->basePath(); ?>/img/shirt/limit.png" title="limit" data-parameters='{"x": 372, "y": 370, "scale": 0.7, "autoCenter": false}'>
	</div>
	
	<!-- Here you can add more product divs -->