

<h2>Nombre de t-shirts</h2>
<div class="sideContent">
	<div id="productNumberSlider">
		<span style="left: 0;">10</span>
		<span style="left: 17%;">200</span>
		<span style="left: 37%;">400</span>
		<span style="left: 57%;">600</span>
		<span style="left: 77%;">800</span>
		<span style="right: 0;">1000</span>
	</div>
	<span class="infos">Prix de base de <span>8,5€</span> avec un objectif de <input type="number" min="10" max="1000" name="shirtNumber" value="20"> t-shirts vendus</span>
	<p>Votre “objectif” est le nombre minimum de t-shirts réservés à atteindre. Les t-shirts seront fabriqués et imprimés uniquement si la campagne atteint son objectif. <a href="#">Savoir pourquoi</a>.</p>
</div><!-- End sideContent -->


<h2>Prix de vente</h2>
<div class="sideContent">
	<div id="productPriceSlider">
		<span style="left: 0;">10</span>
		<span style="left: 9%;">20</span>
		<span style="left: 20%;">30</span>
		<span style="left: 30%;">40</span>
		<span style="left: 53%;">60</span>
		<span style="left: 75%;">80</span>
		<span style="right: 0;">100</span>
	</div>
	<span class="infos">Avec un prix de <span class="productPrice">28</span>€, votre profit par t-shirt est de <span class="profitPerShirt">4,5</span>€</span>
</div><!-- End sideContent -->


<h2>Profit estimé* <span class="profit"> 888,88€</span></h2>
<div class="sideContent">
	<span class="infos">* Si vous vendez <span class="productNumber">28</span> t-shirts au prix de <span class="productPrice">28</span>€</span>
</div><!-- End sideContent -->
<div class="nextStep2 btn1">Etape suivante</div>