<h2>Titre de la campagne</h2>
<div class="sideContent">
	<input type="text" for="campaignTitle">
	<span>Résumez votre campagne en <span>50</span> caractères max.</span>
</div><!-- End sideContent -->

<h2>Description de la campagne</h2>
<div class="sideContent">
	<textarea for="campaignDescription"></textarea>
	<span>Expliqez pourquoi vos potentiels acheteurs devraient acheter votre t-shirt.</span>
	<span>300</span><span> caractères max.</span>
</div><!-- End sideContent -->

<h2>Catégorie de la campagne</h2>
<div class="sideContent">
	<select>
		<option>Humour</option>
		<option>Pute</option>
		<option>BDJ</option>
	</select>
</div><!-- End sideContent -->

<h2>Durée de la campagne</h2>
<div class="sideContent">
	<select>
		<option>10 jours (Date de fin : 28/02/2014</option>
		<option>15 jours (Date de fin : 03/03/2014</option>
		<option>20 jours (Date de fin : 08/03/2014</option>
	</select>
	<span>Une fois cette date passée, votre campagne sera réalisée ou non.</span>
</div><!-- End sideContent -->

<h2>URL de la campagne</h2>
<div class="sideContent">
	<span>www.ouishirt.com/campaing/</span><input type="text">
	<span>Il s'agit de l'adresse faisant référence à votre campagne.</span>
</div><!-- End sideContent -->

<h2>Option de livraison (gratuite)</h2>
<div class="sideContent">
	<input type="checkbox"><label>Les acheteurs peuvent venir chercher leur t-shirt directement chez vous.</label>
</div><!-- End sideContent -->

<h2>Visibilité de la campagne</h2>
<div class="sideContent">
	<input type="checkbox"><label>Rendre ma campagne privée</label>
</div><!-- End sideContent -->

<h2>Conditions générales de ventes</h2>
<div class="sideContent">
	<input type="checkbox"><label>J'ai lu et j'accepte les <a href="#">conditions générales de vente</a></label>
</div><!-- End sideContent -->

<div class="btn1">Démarrer la campagne</div>