



<?php  

//CSS
$this->headLink()	->prependStylesheet($this->basePath() . '/css/vendor/fancy/overwrite.css')
					->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
					->prependStylesheet($this->basePath() . '/css/vendor/fancy/jquery.fancyProductDesigner-fonts.css')
					->prependStylesheet($this->basePath() . '/css/vendor/fancy/jquery.fancyProductDesigner.css')
					->prependStylesheet($this->basePath() . '/css/vendor/fancy/plugins.min.css')
					;        
//JS
$this->headScript()//->prependFile($this->basePath() . '/js/vendor/fancy/jspdf.min.js') //PDF
					->prependFile($this->basePath() . '/js/vendor/fancy/jquery.fancyProductDesigner.js')
					->prependFile($this->basePath() . '/js/vendor/fancy/webfont.js')
					->prependFile($this->basePath() . '/js/vendor/fancy/plugins.min.js')
					->prependFile($this->basePath() . '/js/vendor/fancy/fabric.js')
					
            		;

$this->inlineScript()   ->prependFile($this->basePath('/js/campaign.js'))


?>
<div class="campaignAdd" id="ouishirtDesigner">
	<?php echo $this->partial('campaign/partial/products.phtml'); ?>
	<section id="content" class="grayBackground">
		<div class="wrapper">
			<div id="campaignStatus">
				<?php echo $this->partial('campaign/partial/campaignStatus.phtml'); ?>
			</div><!-- End campaignStatus -->
			<div id="campaignConfig" class="col4">
				<div id="configDesign" class="fpd-sidebar fpd-border-color fpd-clearfix">
					<?php echo $this->partial('campaign/partial/sideDesign.phtml'); ?>
				</div><!-- End configDesign -->
				<div id="configGoal" style="display: none;">
					<?php echo $this->partial('campaign/partial/sideGoal.phtml'); ?>
				</div><!-- End configGoal -->
				<div id="configCampaign" style="display: none;">
					<?php echo $this->partial('campaign/partial/sideCampaign.phtml'); ?>
				</div><!-- End configCampaign -->
			</div><!-- End campaignConfig -->
			<div id="campaignDesign" class="fpd-product-container col8 omega">
				<?php echo $this->partial('campaign/partial/design.phtml'); ?>
			</div><!-- End campaignDesign -->
		</div><!-- End wrapper -->
	</section><!-- End content -->

</div><!-- End campaignAdd -->