    <footer id="footer">
      <section id="preFooter">
        <div class="wrapper">
        </div>
      </section>
      
      <section id="bigFooter">
        <div class="wrapper clearfix">
          <div class="col3">
            <div class="widget">
              <h3><?php echo $this->translate("100% satisfaction", "default", $this->lang_); ?></h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra, enim vel faucibus imperdiet, augue elit interdum magna, sit amet suscipit sapien sapien et dui.</p>
              <p>In imperdiet nisl nec metus varius, non porta velit tempor.</p>
            </div>
          </div>
          
          <div class="col3">
            <div class="widget">
              <h3><?php echo $this->translate("Besoin d'aide ?", "default", $this->lang_); ?></h3>
              <ul>
                <li>
                  <a href="#"><?php echo $this->translate("Comment ça marche ?", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("FAQ", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Livraison", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Guide des tailles", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Contactez-nous", "default", $this->lang_); ?></a>
                </li>
              </ul>
            </div>
            
            <div class="widget">
              <h3><?php echo $this->translate("Newsletter", "default", $this->lang_); ?></h3>
              <p><?php echo $this->translate("Restez au courant de nos nouveautés !", "default", $this->lang_); ?></p>
            </div>
          </div>
          
          <div class="col3">
            <div class="widget">
              <h3><?php echo $this->translate("Plus", "default", $this->lang_); ?></h3>
              <ul>
                <li>
                  <a href="#"><?php echo $this->translate("À propos", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Nos produits", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Entreprises", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("CGV", "default", $this->lang_) . '/' . $this->translate("CGU", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Emplois", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Blog", "default", $this->lang_); ?></a>
                </li>
              </ul>
            </div>
          </div>
          
          <div class="col3 omega">
            <div class="widget">
              <h3><?php echo $this->translate("Votre compte", "default", $this->lang_); ?></h3>
              <ul>
                <li>
                  <a href="#"><?php echo $this->translate("Se connecter", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Votre commande", "default", $this->lang_); ?></a>
                </li>
                <li>
                  <a href="#"><?php echo $this->translate("Frais d'envoi", "default", $this->lang_); ?></a>
                </li>
              </ul>
            </div>
            
            <div class="widget">
              <h3><?php echo $this->translate("Nous acceptons", "default", $this->lang_); ?></h3>
              <img src="<?php echo $this->basePath(); ?>/img/cards.png">
            </div>
          </div>
        </div>
        </div>
        
        <div id="copyright" class="wrapper clearfix">
          <p>© Ouishirt 2014 made with love in Belgium</p>
        </div>
      </section>
    </footer>