    <footer id="footer">
      <section id="preFooter">
        <div class="wrapper">
        </div>
      </section>
      
      <section id="bigFooter">
        <div class="wrapper clearfix">
          <div class="col3">
            <div class="widget">
              <h3>100% satisfaction</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra, enim vel faucibus imperdiet, augue elit interdum magna, sit amet suscipit sapien sapien et dui.</p>
              <p>In imperdiet nisl nec metus varius, non porta velit tempor.</p>
            </div>
          </div>
          
          <div class="col3">
            <div class="widget">
              <h3>Des question&nbsp;?</h3>
              <ul>
                <li>
                  <a href="#">Aide "ouishirt"</a>
                </li>
                <li>
                  <a href="#">Formulaire de contact</a>
                </li>
                <li>
                  +32 xxx xx xx xx
                </li>
              </ul>
            </div>
            
            <div class="widget">
              <h3>Newsletter</h3>
              <p>Restez au courant de nos nouveautés&nbsp;!</p>
            </div>
          </div>
          
          <div class="col3">
            <div class="widget">
              <h3>Plus</h3>
              <ul>
                <li>
                  <a href="#">À propos</a>
                </li>
                <li>
                  <a href="#">Livraison</a>
                </li>
                <li>
                  <a href="#">Emplois</a>
                </li>
                <li>
                  <a href="#">F.A.Q</a>
                </li>
                <li>
                  <a href="#">Conditions générales</a>
                </li>
                <li>
                  <a href="#">Mentions légales</a>
                </li>
              </ul>
            </div>
          </div>
          
          <div class="col3 omega">
            <div class="widget">
              <h3>Votre compte</h3>
              <ul>
                <li>
                  <a href="#">Se connecter</a>
                </li>
                <li>
                  <a href="#">Votre commande</a>
                </li>
                <li>
                  <a href="#">Frais d'envoi</a>
                </li>
              </ul>
            </div>
            
            <div class="widget">
              <h3>Nous acceptons</h3>
              <img src="./img/cards.png"
            </div>
          </div>
        </div>
        </div>
        
        <div id="copyright" class="wrapper clearfix">
          <p>© Ouishirt 2014</p>
        </div>
      </section>
    </footer>