      <header>
        <div id="topBar" class="">
          <div class="wrapper clearfix">
            <p class="left">Vous représentez une cause ou un projet&nbsp;? <a href="#">En savoir plus&nbsp;!</a></p>

            <div id="loginBox" class="right">
            </div>
          </div>
        </div>
        
        <div id="mainBar" class="">
          <div class="wrapper clearfix">
            <h1 id="logo">ouishirt</h1>
            
            <ul id="nav" class="clearfix">
              <li class="left">
                <a href="#">Explorer</a>
              </li>
              <li class="left">
                <a href="#">Comment ça marche&nbsp;?</a>
              </li>
              <li class="left">
                <a href="#">Campagnes</a>
              </li>
            </ul>
          </div>
        </div>
      </header>