<?php echo $this->serverUrl(true);  ?>
<?php  echo $this->ZfcUserLoginWidget(array('redirect' => $this->serverUrl(true))); ?>
<?php // echo $this->ZfcUserLoginWidget(); ?>
<?php 
echo $this->translate("Home", "default", $this->lang_)."<br>";
echo $this->translate("Test de la mort", "default", $this->lang_)."<br>";
 ?>
<?php echo $this->lang_."<br>"; ?>
<?php echo $this->basePath()."<br>"; ?>
<?php echo $this->partial('layout/languages.phtml', array(
                    'lang' => array(
                        'English'  => 'en-US',
                        'Français' => 'fr-FR',
                        'Deutsch'  => 'de-DE',
                    ),
                    'selected' => $this->lang,
              )); ?>
      <header>
        <div id="topBar" class="">
          <div class="wrapper clearfix">
            <p class="left">Vous représentez une cause ou un projet&nbsp;? <a href="#">En savoir plus&nbsp;!</a></p>

            <div id="loginBox" class="right">
            </div>
          </div>
        </div>
        
        <div id="mainBar" class="">
          <div class="wrapper clearfix">
            <h1 id="logo">ouishirt</h1>
            
            <ul id="nav" class="clearfix">
              <li class="left">
                <a href="#">Explorer</a>
              </li>
              <li class="left">
                <a href="#">Comment ça marche&nbsp;?</a>
              </li>
              <li class="left">
                <a href="<?php echo $this->url('campaign', array('lang' => $this->lang , 'action' => 'index')); ?>">Campagnes</a>
              </li>
            </ul>
          </div>
        </div>
      </header>