<select id="select01" style="margin-top:5px; width: 100px"
        onChange="javascript:window.location.replace(changeLang(this.value));">
    <?php 
    	foreach ($this->lang as $key => $value) {
        $selected = ($value === $this->selected) ? ' selected' : '';
        printf(
            '<option value="%s"%s>%s</option>',
            $this->escapeHtmlAttr($value),
            $selected,
            $this->escapeHtml($key)
        );
    } ?>
</select>
<script language="JavaScript">
    function changeLang(lang) {
        var slashIndex = 33; //LOCAL
        //var slashIndex = 20; //ONLINE
        var startUrl = location.href.slice(0, slashIndex);
        var endUrl = location.href.slice(slashIndex+2);
        var newUrl = startUrl + lang + endUrl;

        if (newUrl != location.href) {
            return newUrl;
        }
        var n = location.href.indexOf('/',slashIndex);
        if (location.href.substr(n) == '/') {
            return location.href.substr(0,n) + '/' + lang;
        }
        return location.href.substr(0,n) + '/' + lang + location.href.substr(n);
    }
</script>