<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/retina.css')
                        ->prependStylesheet($this->basePath() . '/css/responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/print.css')
                        ->prependStylesheet($this->basePath() . '/css/screen.css') ?>
        <link href="./stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="index">
        <div id="root">
            <?php echo $this->partial('header'); ?>
            <?php echo $this->content; ?>
        </div><!--end root -->
        <?php echo $this->partial('footer'); ?>
        <?php echo $this->inlineScript() ?>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>
        
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='http://www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
