<?php 
//start session service
$session = new \Zend\Session\Container('ouishirt');
//Store current url
$currentUrl = $this->serverUrl(true);
echo $currentUrl.' COUCOU<br>';
//check if we are NOT on login/register page
if (strpos($currentUrl, 'login') == false AND strpos($currentUrl, 'register') == false) {
    //Store current url
    $session->url = $currentUrl;
}
echo $session->url;
?>



<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Title -->
        <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>
        <!-- Meta -->
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>
        <!-- Google Font -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/print.css')
                        ->prependStylesheet($this->basePath() . '/css/responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/retina.css')
                        ->prependStylesheet($this->basePath() . '/css/screen.css', 'screen, projection')
                        ->prependStylesheet($this->basePath() . '/css/normalize.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2.min.js')
        ; ?>

    </head>
    <body class="index">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
        <div id="root">
            <?php echo $this->partial('header'); ?>
            <?php echo $this->content; ?>
        </div><!--end root -->
        <?php echo $this->partial('footer'); ?>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>
        <?php 
            echo $this->inlineScript()->prependFile($this->basePath('js/plugins.js'))
                                      ->prependFile($this->basePath('js/main.js'))
         ;?>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='http://www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
