
      <section id="slider">
        <div class="wrapper">
          <img src="<?php echo $this->basePath(); ?>/img/slider.jpg" />
        </div>
      </section>
      
      <section id="content" class="grayBackground">
        <div class="wrapper">
          <div class="centerBloc">
            <h2>Nos campagnes <strong>à la une</strong></h2>
          </div>
          
          <ul class="clearfix">
            
            <li class="col4 campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>125</strong>/1250 pré-commandes</p>
                  <p class="right percentage">10%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 10%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
            
            <li class="col4 campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>250</strong>/1250 pré-commandes</p>
                  <p class="right percentage">20%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 20%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
            
            <li class="col4 omega campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>500</strong>/1250 pré-commandes</p>
                  <p class="right percentage">40%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 40%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
            
            <li class="col4 campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>1000</strong>/1250 pré-commandes</p>
                  <p class="right percentage">80%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 80%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
            
            <li class="col4 campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>125</strong>/1250 pré-commandes</p>
                  <p class="right percentage">10%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 10%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
            
            <li class="col4 omega campaignBloc">
              <div class="campaignImage">
                <img src="<?php echo $this->basePath(); ?>/img/testShirt.jpg" />
                <h3>Brasil red devils<strong class="price">25€</strong></h3>
              </div>
              <div class="campaignInfos clearfix">
                <div class="clearfix">
                  <p class="left preOrderQuantity"><strong>750</strong>/1250 pré-commandes</p>
                  <p class="right percentage">50%</p>
                </div>
                
                <div class="progressBar">
                  <div class="progressValue" style="width: 50%;"></div>
                </div>
                
                <p class="left daysLeft"><strong>30 jours</strong> restants</p>
                
                <a href="#" class="right btn1">Voir la campagne</a>
              </div>
            </li>
          </ul>
          
          <div class="centerBloc">
            <a href="#" class="btn2">Voir plus de campagnes</a>
          </div>
        </div>
      </section> <!-- End of #content -->
      <div id="root_footer">
      </div>